permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "h1mmel"
email: xiaoxiaoxiaotian@gmail.com
description: ""
github:
  username: h1mmel
swiftype:
  searchId: 
gitment:
    repo: blog
    client_id: 
    client_secret: 

url: "https://h1mmel.github.io"
imgrepo: "https://h1mmel.github.io/static/img"

